# -*- coding: utf-8 -*-
"""app11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KTdoxvUqMonEXhgWa3RJLiDBDltJGdks
"""

# ============================================
# File: dashboard/app.py
#
# Interactive dashboard for non-technical stakeholders.
# Mint Green Theme — Light background, dark text.
# ============================================

import streamlit as st
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots
import requests
import json
import os
import time
import numpy as np
from datetime import datetime, timedelta

# ============================================
# Page configuration
# ============================================

st.set_page_config(
    page_title="Demand Forecasting Dashboard",
    page_icon="📊",
    layout="wide",
    initial_sidebar_state="expanded"
)

# ============================================
# CUSTOM CSS — Mint Green Theme
# ============================================

st.markdown("""
<style>
    /* ===== GLOBAL STYLES ===== */
    @import url('https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800&display=swap');

    /* Force light mint background everywhere */
    .stApp {
        font-family: 'Inter', sans-serif;
        background-color: #e8f6ef !important;
        color: #1a2332 !important;
    }

    /* Override Streamlit's dark defaults */
    .stApp > header {
        background-color: #e8f6ef !important;
    }

    .main .block-container {
        background-color: #e8f6ef !important;
        color: #1a2332 !important;
    }

    /* All text defaults to dark */
    .stApp, .stApp p, .stApp span, .stApp div, .stApp label,
    .stApp h1, .stApp h2, .stApp h3, .stApp h4, .stApp h5, .stApp h6 {
        color: #1a2332 !important;
    }

    /* Override Streamlit markdown text */
    .stMarkdown, .stMarkdown p, .stMarkdown span,
    .stMarkdown li, .stMarkdown td, .stMarkdown th {
        color: #1a2332 !important;
    }

    /* Hide default Streamlit branding */
    #MainMenu {visibility: hidden;}
    footer {visibility: hidden;}
    header {visibility: hidden;}

    /* ===== SCROLLBAR ===== */
    ::-webkit-scrollbar {
        width: 8px;
        height: 8px;
    }
    ::-webkit-scrollbar-track {
        background: #d4edda;
    }
    ::-webkit-scrollbar-thumb {
        background: linear-gradient(180deg, #2d6a4f, #40916c);
        border-radius: 10px;
    }

    /* ===== HERO BANNER ===== */
    .hero-banner {
        background: linear-gradient(135deg, #2d6a4f 0%, #40916c 50%, #52b788 100%);
        padding: 2.5rem 2rem;
        border-radius: 20px;
        margin-bottom: 2rem;
        position: relative;
        overflow: hidden;
        box-shadow: 0 15px 40px rgba(45, 106, 79, 0.3);
    }
    .hero-banner::before {
        content: '';
        position: absolute;
        top: -50%;
        right: -20%;
        width: 400px;
        height: 400px;
        background: rgba(255,255,255,0.07);
        border-radius: 50%;
    }
    .hero-banner::after {
        content: '';
        position: absolute;
        bottom: -30%;
        left: -10%;
        width: 300px;
        height: 300px;
        background: rgba(255,255,255,0.04);
        border-radius: 50%;
    }
    .hero-banner h1 {
        color: #ffffff !important;
        font-size: 2.4rem;
        font-weight: 800;
        margin: 0;
        letter-spacing: -0.5px;
    }
    .hero-banner p {
        color: rgba(255,255,255,0.9) !important;
        font-size: 1.1rem;
        margin-top: 0.5rem;
        font-weight: 300;
    }
    .hero-badge {
        display: inline-block;
        background: rgba(255,255,255,0.2);
        backdrop-filter: blur(10px);
        padding: 0.3rem 0.8rem;
        border-radius: 20px;
        color: #ffffff !important;
        font-size: 0.8rem;
        font-weight: 500;
        margin-top: 0.5rem;
        margin-right: 0.3rem;
        border: 1px solid rgba(255,255,255,0.3);
    }

    /* ===== METRIC CARDS ===== */
    .metric-card {
        background: #ffffff;
        border: 1px solid rgba(45, 106, 79, 0.12);
        border-radius: 16px;
        padding: 1.5rem;
        text-align: center;
        transition: all 0.4s cubic-bezier(0.4, 0, 0.2, 1);
        position: relative;
        overflow: hidden;
        box-shadow: 0 4px 15px rgba(0,0,0,0.06);
    }
    .metric-card:hover {
        transform: translateY(-8px);
        box-shadow: 0 20px 40px rgba(45, 106, 79, 0.15);
        border-color: rgba(45, 106, 79, 0.3);
    }
    .metric-card::before {
        content: '';
        position: absolute;
        top: 0;
        left: 0;
        right: 0;
        height: 4px;
        border-radius: 16px 16px 0 0;
    }
    .metric-card.emerald::before {
        background: linear-gradient(90deg, #2d6a4f, #52b788);
    }
    .metric-card.teal::before {
        background: linear-gradient(90deg, #0f9b8e, #38d9a9);
    }
    .metric-card.sky::before {
        background: linear-gradient(90deg, #3b82f6, #60a5fa);
    }
    .metric-card.amber::before {
        background: linear-gradient(90deg, #d97706, #fbbf24);
    }
    .metric-icon {
        font-size: 2rem;
        margin-bottom: 0.5rem;
    }
    .metric-value {
        font-size: 2rem;
        font-weight: 800;
        -webkit-background-clip: text;
        -webkit-text-fill-color: transparent;
        background-clip: text;
    }
    .metric-value.emerald-text {
        background: linear-gradient(135deg, #2d6a4f, #40916c);
        -webkit-background-clip: text;
        background-clip: text;
    }
    .metric-value.teal-text {
        background: linear-gradient(135deg, #0f9b8e, #38d9a9);
        -webkit-background-clip: text;
        background-clip: text;
    }
    .metric-value.sky-text {
        background: linear-gradient(135deg, #3b82f6, #60a5fa);
        -webkit-background-clip: text;
        background-clip: text;
    }
    .metric-value.amber-text {
        background: linear-gradient(135deg, #d97706, #f59e0b);
        -webkit-background-clip: text;
        background-clip: text;
    }
    .metric-label {
        color: #6b7280 !important;
        font-size: 0.8rem;
        font-weight: 600;
        text-transform: uppercase;
        letter-spacing: 1px;
        margin-top: 0.3rem;
    }
    .metric-delta {
        font-size: 0.78rem;
        padding: 0.2rem 0.6rem;
        border-radius: 20px;
        display: inline-block;
        margin-top: 0.5rem;
        font-weight: 600;
    }
    .metric-delta.positive {
        background: rgba(45, 106, 79, 0.1);
        color: #2d6a4f !important;
    }

    /* ===== GLASS CARDS (now white glass) ===== */
    .glass-card {
        background: rgba(255,255,255,0.7);
        backdrop-filter: blur(20px);
        border: 1px solid rgba(45, 106, 79, 0.1);
        border-radius: 16px;
        padding: 1.5rem;
        margin-bottom: 1rem;
        transition: all 0.3s ease;
        box-shadow: 0 2px 10px rgba(0,0,0,0.04);
    }
    .glass-card:hover {
        border-color: rgba(45, 106, 79, 0.25);
        background: rgba(255,255,255,0.85);
        box-shadow: 0 8px 25px rgba(0,0,0,0.08);
    }
    .glass-card h3 {
        color: #1a2332 !important;
    }

    /* ===== PREDICTION RESULT BOX ===== */
    .prediction-result {
        background: linear-gradient(135deg, rgba(45,106,79,0.08), rgba(82,183,136,0.05));
        border: 2px solid rgba(45, 106, 79, 0.25);
        border-radius: 20px;
        padding: 2rem;
        text-align: center;
        animation: fadeInUp 0.6s ease;
    }
    .prediction-value {
        font-size: 3rem;
        font-weight: 800;
        background: linear-gradient(135deg, #2d6a4f, #52b788);
        -webkit-background-clip: text;
        -webkit-text-fill-color: transparent;
        background-clip: text;
    }
    .prediction-label {
        color: #6b7280 !important;
        font-size: 0.9rem;
        text-transform: uppercase;
        letter-spacing: 2px;
        margin-bottom: 0.5rem;
    }
    .prediction-units {
        color: #9ca3af !important;
        font-size: 0.9rem;
        margin-top: 0.3rem;
    }

    /* ===== TAB STYLING ===== */
    .stTabs [data-baseweb="tab-list"] {
        gap: 8px;
        background: rgba(255,255,255,0.6);
        border-radius: 12px;
        padding: 0.5rem;
        border: 1px solid rgba(45,106,79,0.08);
    }
    .stTabs [data-baseweb="tab"] {
        border-radius: 10px;
        padding: 0.7rem 1.5rem;
        font-weight: 600;
        font-size: 0.9rem;
        color: #6b7280 !important;
        background: transparent;
        border: none;
    }
    .stTabs [aria-selected="true"] {
        background: linear-gradient(135deg, #2d6a4f, #40916c) !important;
        color: #ffffff !important;
        box-shadow: 0 4px 15px rgba(45, 106, 79, 0.3);
    }
    .stTabs [data-baseweb="tab-highlight"] {
        display: none;
    }
    .stTabs [data-baseweb="tab-border"] {
        display: none;
    }

    /* ===== BUTTONS ===== */
    .stButton > button[kind="primary"] {
        background: linear-gradient(135deg, #2d6a4f, #40916c) !important;
        color: #ffffff !important;
        border: none !important;
        border-radius: 12px !important;
        padding: 0.8rem 2rem !important;
        font-weight: 700 !important;
        font-size: 1rem !important;
        letter-spacing: 0.5px;
        box-shadow: 0 8px 25px rgba(45, 106, 79, 0.3);
        transition: all 0.3s ease !important;
    }
    .stButton > button[kind="primary"]:hover {
        transform: translateY(-2px) !important;
        box-shadow: 0 12px 35px rgba(45, 106, 79, 0.45) !important;
    }
    .stButton > button {
        color: #1a2332 !important;
    }

    /* ===== SIDEBAR ===== */
    section[data-testid="stSidebar"] {
        background: linear-gradient(180deg, #f0faf4 0%, #d8f3e3 100%) !important;
        border-right: 1px solid rgba(45, 106, 79, 0.12);
    }
    section[data-testid="stSidebar"] .stMarkdown h1,
    section[data-testid="stSidebar"] .stMarkdown h2,
    section[data-testid="stSidebar"] .stMarkdown h3,
    section[data-testid="stSidebar"] .stMarkdown p,
    section[data-testid="stSidebar"] .stMarkdown span,
    section[data-testid="stSidebar"] .stMarkdown label,
    section[data-testid="stSidebar"] .stMarkdown div,
    section[data-testid="stSidebar"] p,
    section[data-testid="stSidebar"] span,
    section[data-testid="stSidebar"] label {
        color: #1a2332 !important;
    }
    section[data-testid="stSidebar"] .stMarkdown h1 {
        font-size: 1.3rem;
        font-weight: 700;
    }

    /* Sidebar radio / selectbox text */
    section[data-testid="stSidebar"] .stRadio label,
    section[data-testid="stSidebar"] .stSelectbox label,
    section[data-testid="stSidebar"] .stCheckbox label {
        color: #1a2332 !important;
    }

    /* ===== INPUT FIELDS ===== */
    .stNumberInput > div > div > input,
    .stSelectbox > div > div {
        border-radius: 10px !important;
        border: 1px solid rgba(45, 106, 79, 0.2) !important;
        background: #ffffff !important;
        color: #1a2332 !important;
        transition: all 0.3s ease;
    }
    .stNumberInput > div > div > input:focus {
        border-color: #2d6a4f !important;
        box-shadow: 0 0 0 3px rgba(45, 106, 79, 0.15) !important;
    }
    .stNumberInput label, .stSelectbox label, .stSlider label {
        color: #1a2332 !important;
    }

    /* Toggle / checkbox */
    .stCheckbox span, .stToggle span {
        color: #1a2332 !important;
    }

    /* Radio buttons */
    .stRadio label span {
        color: #1a2332 !important;
    }

    /* Slider */
    .stSlider label, .stSlider span {
        color: #1a2332 !important;
    }

    /* Caption text */
    .stCaption, .stApp small, .stApp caption {
        color: #6b7280 !important;
    }

    /* ===== ANIMATIONS ===== */
    @keyframes fadeInUp {
        from { opacity: 0; transform: translateY(30px); }
        to { opacity: 1; transform: translateY(0); }
    }
    @keyframes fadeIn {
        from { opacity: 0; }
        to { opacity: 1; }
    }
    @keyframes pulse {
        0%, 100% { opacity: 1; }
        50% { opacity: 0.6; }
    }
    @keyframes slideInLeft {
        from { opacity: 0; transform: translateX(-30px); }
        to { opacity: 1; transform: translateX(0); }
    }
    .animate-fade-in { animation: fadeIn 0.8s ease; }
    .animate-fade-up { animation: fadeInUp 0.6s ease; }
    .animate-slide-left { animation: slideInLeft 0.5s ease; }

    /* ===== INSIGHT BOXES ===== */
    .insight-box {
        background: linear-gradient(135deg, rgba(59,130,246,0.08), rgba(96,165,250,0.04));
        border-left: 4px solid #3b82f6;
        border-radius: 0 12px 12px 0;
        padding: 1.2rem 1.5rem;
        margin: 1rem 0;
    }
    .insight-box h4 {
        margin: 0 0 0.5rem 0;
        font-size: 1rem;
        color: #1a2332 !important;
    }
    .insight-box p {
        margin: 0;
        color: #4a5568 !important;
        font-size: 0.9rem;
        line-height: 1.6;
    }
    .insight-box strong {
        color: #1a2332 !important;
    }
    .insight-box.warning {
        background: linear-gradient(135deg, rgba(217,119,6,0.08), rgba(251,191,36,0.04));
        border-left-color: #d97706;
    }
    .insight-box.success {
        background: linear-gradient(135deg, rgba(45,106,79,0.08), rgba(82,183,136,0.04));
        border-left-color: #2d6a4f;
    }

    /* ===== ARCHITECTURE DIAGRAM ===== */
    .arch-step {
        background: #ffffff;
        border: 1px solid rgba(45, 106, 79, 0.12);
        border-radius: 12px;
        padding: 1rem;
        text-align: center;
        transition: all 0.3s ease;
        box-shadow: 0 2px 8px rgba(0,0,0,0.04);
    }
    .arch-step:hover {
        border-color: #2d6a4f;
        transform: scale(1.03);
        box-shadow: 0 8px 20px rgba(45,106,79,0.12);
    }
    .arch-icon { font-size: 2rem; margin-bottom: 0.5rem; }
    .arch-title {
        font-weight: 700;
        font-size: 0.85rem;
        color: #1a2332 !important;
    }
    .arch-desc {
        font-size: 0.75rem;
        color: #6b7280 !important;
    }
    .arch-arrow {
        display: flex;
        align-items: center;
        justify-content: center;
        font-size: 1.5rem;
        color: #2d6a4f !important;
    }

    /* ===== SECTION HEADERS ===== */
    .section-header {
        display: flex;
        align-items: center;
        gap: 0.8rem;
        margin-bottom: 1.5rem;
    }
    .section-header .icon {
        background: linear-gradient(135deg, #2d6a4f, #40916c);
        width: 45px;
        height: 45px;
        border-radius: 12px;
        display: flex;
        align-items: center;
        justify-content: center;
        font-size: 1.3rem;
    }
    .section-header .text h2 {
        margin: 0;
        font-size: 1.4rem;
        font-weight: 700;
        color: #1a2332 !important;
    }
    .section-header .text p {
        margin: 0;
        color: #6b7280 !important;
        font-size: 0.85rem;
    }

    /* ===== FOOTER ===== */
    .custom-footer {
        background: #ffffff;
        border: 1px solid rgba(45,106,79,0.1);
        border-radius: 16px;
        padding: 1.5rem;
        text-align: center;
        margin-top: 3rem;
        box-shadow: 0 2px 10px rgba(0,0,0,0.04);
    }
    .custom-footer p {
        color: #6b7280 !important;
        font-size: 0.8rem;
        margin: 0;
    }
    .footer-links a {
        color: #2d6a4f !important;
        text-decoration: none;
        margin: 0 0.5rem;
        font-weight: 600;
    }
    .footer-links a:hover {
        color: #40916c !important;
        text-decoration: underline;
    }

    /* ===== STAT PILL ===== */
    .stat-pill {
        display: inline-block;
        background: rgba(45, 106, 79, 0.1);
        color: #2d6a4f !important;
        padding: 0.35rem 0.9rem;
        border-radius: 20px;
        font-size: 0.8rem;
        font-weight: 600;
        margin: 0.2rem;
        border: 1px solid rgba(45,106,79,0.15);
    }

    /* ===== LIVE INDICATOR ===== */
    .live-dot {
        display: inline-block;
        width: 8px;
        height: 8px;
        background: #2d6a4f;
        border-radius: 50%;
        margin-right: 6px;
        animation: pulse 2s infinite;
    }

    /* ===== COMPARISON TABLE ===== */
    .comparison-table {
        width: 100%;
        border-collapse: separate;
        border-spacing: 0 8px;
    }
    .comparison-table th {
        background: rgba(45, 106, 79, 0.1);
        color: #2d6a4f !important;
        padding: 0.8rem 1rem;
        text-align: left;
        font-weight: 600;
        font-size: 0.85rem;
        text-transform: uppercase;
        letter-spacing: 1px;
    }
    .comparison-table td {
        background: #ffffff;
        padding: 0.8rem 1rem;
        color: #1a2332 !important;
        border-top: 1px solid rgba(45,106,79,0.06);
        border-bottom: 1px solid rgba(45,106,79,0.06);
    }
    .comparison-table tr:hover td {
        background: rgba(45, 106, 79, 0.04);
    }
    .comparison-table th:first-child { border-radius: 8px 0 0 8px; }
    .comparison-table th:last-child { border-radius: 0 8px 8px 0; }
    .comparison-table td:first-child { border-radius: 8px 0 0 8px; }
    .comparison-table td:last-child { border-radius: 0 8px 8px 0; }

    /* ===== SIDEBAR GLASS CARD ===== */
    .sidebar-status-card {
        background: rgba(255,255,255,0.6);
        border: 1px solid rgba(45,106,79,0.12);
        border-radius: 12px;
        padding: 1rem;
        margin-bottom: 0.5rem;
    }
    .sidebar-status-card p {
        color: #1a2332 !important;
        font-weight: 600;
        margin-bottom: 0.6rem;
        font-size: 0.85rem;
    }
    .sidebar-status-item {
        display: flex;
        align-items: center;
        margin: 0.4rem 0;
    }
    .sidebar-status-item span.status-text {
        color: #2d6a4f !important;
        font-size: 0.8rem;
        font-weight: 500;
    }

    /* ===== SIDEBAR LINKS ===== */
    .sidebar-link {
        display: block;
        color: #1a2332 !important;
        text-decoration: none;
        font-size: 0.85rem;
        padding: 0.5rem 0.7rem;
        border-radius: 8px;
        background: rgba(255,255,255,0.4);
        margin-bottom: 0.4rem;
        transition: all 0.3s;
        border: 1px solid rgba(45,106,79,0.08);
    }
    .sidebar-link:hover {
        background: rgba(255,255,255,0.8);
        border-color: rgba(45,106,79,0.2);
    }

    /* ===== ABOUT SECTION PROFILE ===== */
    .profile-card {
        background: #ffffff;
        border: 1px solid rgba(45,106,79,0.12);
        border-radius: 16px;
        padding: 1.5rem;
        box-shadow: 0 4px 15px rgba(0,0,0,0.05);
    }
    .profile-card h3 {
        color: #1a2332 !important;
        margin: 0;
    }
    .profile-card .subtitle {
        color: #6b7280 !important;
        margin: 0.2rem 0;
    }
    .profile-card .edu {
        color: #9ca3af !important;
        font-size: 0.85rem;
    }
    .profile-card a {
        color: #2d6a4f !important;
        text-decoration: none;
        font-weight: 600;
    }
    .profile-card a:hover {
        color: #40916c !important;
        text-decoration: underline;
    }

    /* ===== PROBLEM STATEMENT CARD ===== */
    .problem-card {
        background: #ffffff;
        border: 1px solid rgba(45,106,79,0.12);
        border-radius: 16px;
        padding: 1.5rem;
        box-shadow: 0 4px 15px rgba(0,0,0,0.05);
    }
    .problem-card h3 {
        color: #1a2332 !important;
        margin-top: 0;
    }
    .problem-card p {
        color: #4a5568 !important;
        line-height: 1.8;
    }
    .problem-card strong.highlight-red {
        color: #dc2626 !important;
    }

    /* ===== QUICK COMPARISON CARD ===== */
    .comparison-card {
        background: rgba(255,255,255,0.7);
        border: 1px solid rgba(45,106,79,0.1);
        border-radius: 12px;
        padding: 1rem;
        margin-top: 1rem;
    }
    .comparison-card p.label-text {
        font-size: 0.85rem;
        color: #6b7280 !important;
        margin-bottom: 0.5rem;
    }
    .comparison-card p.value-text {
        font-size: 0.9rem;
        color: #1a2332 !important;
    }

    /* ===== IMPACT CARD DESCRIPTION ===== */
    .impact-desc {
        color: #6b7280 !important;
        font-size: 0.8rem;
        margin-top: 0.8rem;
    }

    /* ===== DOWNLOAD BUTTON ===== */
    .stDownloadButton > button {
        background: #ffffff !important;
        color: #2d6a4f !important;
        border: 2px solid #2d6a4f !important;
        border-radius: 10px !important;
        font-weight: 600 !important;
        transition: all 0.3s ease !important;
    }
    .stDownloadButton > button:hover {
        background: #2d6a4f !important;
        color: #ffffff !important;
    }

    /* ===== PROGRESS BAR ===== */
    .stProgress > div > div > div > div {
        background: linear-gradient(90deg, #2d6a4f, #52b788) !important;
    }
</style>
""", unsafe_allow_html=True)


# ============================================
# Load static results data
# ============================================

@st.cache_data
def load_results():
    """Load model comparison results."""
    base_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    results_path = os.path.join(base_dir, 'results', 'model_results.csv')
    if os.path.exists(results_path):
        return pd.read_csv(results_path)

    return pd.DataFrame({
        'Model': [
            'Baseline (7-Day MA)', 'Linear Regression',
            'Random Forest', 'XGBoost', 'LightGBM'
        ],
        'MAE':  [245.3, 198.5, 156.2, 134.7, 131.2],
        'RMSE': [412.6, 334.1, 267.9, 228.5, 225.7],
        'MAPE': [38.42, 31.20, 24.56, 20.12, 19.45],
        'R²':   [0.6234, 0.7521, 0.8412, 0.8845, 0.8887]
    })


@st.cache_data
def load_feature_importance():
    """Load feature importance data."""
    base_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    fi_path = os.path.join(base_dir, 'results', 'feature_importance.csv')
    if os.path.exists(fi_path):
        return pd.read_csv(fi_path)

    return pd.DataFrame({
        'Feature': [
            'rolling_mean_7', 'sales_lag_7', 'category_avg_all_stores',
            'sales_lag_14', 'sales_lag_1', 'expanding_std',
            'sales_lag_28', 'cluster', 'rolling_std_7',
            'rolling_max_7', 'rolling_max_14', 'expanding_mean',
            'rolling_std_14', 'rolling_mean_30', 'day_of_month'
        ],
        'Importance': [
            0.4987, 0.3225, 0.1060,
            0.0219, 0.0105, 0.0093,
            0.0050, 0.0028, 0.0022,
            0.0019, 0.0014, 0.0013,
            0.0010, 0.0010, 0.0010
        ],
        'Business Meaning': [
            '7-Day Average', 'Same Day Last Week', 'Category Average of All Stores',
            '2 Weeks Ago Sales', "Yesterday's Sales", 'Cumulative Sales Volatility',
            '28 Days Ago Sales', 'Store/Product Segment Group', '7-Day Volatility',
            '7-Day Peak', '14-Day Peak', 'Historical Cumulative Average',
            '14-Day Volatility', '30-Day Average', 'Day of Month'
        ]
    })


results_df = load_results()
importance_df = load_feature_importance()

# ============================================
# Plotly chart template (mint-green-friendly)
# ============================================

CHART_BG = 'rgba(0,0,0,0)'       # transparent so page bg shows
CHART_FONT_COLOR = '#1a2332'
CHART_GRID_COLOR = 'rgba(45,106,79,0.08)'
CHART_COLORS = ['#2d6a4f', '#40916c', '#52b788', '#3b82f6', '#d97706']


# ============================================
# SIDEBAR
# ============================================

with st.sidebar:
    st.markdown("""
    <div style="text-align: center; padding: 1rem 0;">
        <div style="font-size: 3rem;">📊</div>
        <h1 style="
            background: linear-gradient(135deg, #2d6a4f, #40916c);
            -webkit-background-clip: text;
            -webkit-text-fill-color: transparent;
            font-size: 1.4rem;
            margin: 0.5rem 0;
        ">DemandCast AI</h1>
        <p style="color: #6b7280 !important; font-size: 0.8rem;">
            Intelligent Demand Forecasting
        </p>
    </div>
    """, unsafe_allow_html=True)

    st.markdown("---")

    # System status
    st.markdown("""
    <div class="sidebar-status-card">
        <p>⚡ System Status</p>
        <div class="sidebar-status-item">
            <span class="live-dot"></span>
            <span class="status-text">Dashboard Online</span>
        </div>
        <div class="sidebar-status-item">
            <span class="live-dot"></span>
            <span class="status-text">Model Loaded</span>
        </div>
    </div>
    """, unsafe_allow_html=True)

    st.markdown("---")

    # Display settings
    st.markdown("**⚙️ Display Settings**")
    show_annotations = st.checkbox("Show Chart Annotations", value=True)

    st.markdown("---")

    # Model selector
    st.markdown("**🤖 Model Selection**")
    selected_model = st.radio(
        "Active Prediction Model",
        ["LightGBM", "XGBoost (Best)", "Random Forest"],
        index=0
    )

    st.markdown("---")

    # Quick links
    st.markdown("**🔗 Quick Links**")
    st.markdown("""
    <a class="sidebar-link" href="#">📄 API Documentation</a>
    <a class="sidebar-link" href="#">📓 Model Notebook</a>
    <a class="sidebar-link" href="https://github.com/anushkundu" target="_blank">
        🐙 GitHub Repo
    </a>
    """, unsafe_allow_html=True)


# ============================================
# HERO BANNER
# ============================================

st.markdown(f"""
<div class="hero-banner">
    <h1>📊 DemandCast AI</h1>
    <p>ML-powered demand predictions for retail inventory optimization</p>
    <div>
        <span class="hero-badge">🚀 v1.0 Production</span>
        <span class="hero-badge">🤖 {selected_model}</span>
        <span class="hero-badge">📅 {datetime.now().strftime('%b %d, %Y')}</span>
    </div>
</div>
""", unsafe_allow_html=True)


# ============================================
# KEY METRICS ROW
# ============================================

best_mape = results_df['MAPE'].min()
baseline_mape = results_df['MAPE'].max()
improvement = round((baseline_mape - best_mape) / baseline_mape * 100, 1)
best_r2 = results_df['R²'].max()

col1, col2, col3, col4 = st.columns(4)

with col1:
    st.markdown(f"""
    <div class="metric-card emerald">
        <div class="metric-icon">🎯</div>
        <div class="metric-value emerald-text">{best_mape}%</div>
        <div class="metric-label">Best Model MAPE</div>
        <div class="metric-delta positive">↓ {improvement}% vs baseline</div>
    </div>
    """, unsafe_allow_html=True)

with col2:
    st.markdown(f"""
    <div class="metric-card teal">
        <div class="metric-icon">🏆</div>
        <div class="metric-value teal-text">{best_r2:.2%}</div>
        <div class="metric-label">R² Accuracy</div>
        <div class="metric-delta positive">Top performer</div>
    </div>
    """, unsafe_allow_html=True)

with col3:
    st.markdown(f"""
    <div class="metric-card sky">
        <div class="metric-icon">💰</div>
        <div class="metric-value sky-text">$192K</div>
        <div class="metric-label">Annual Savings</div>
        <div class="metric-delta positive">↑ Projected ROI</div>
    </div>
    """, unsafe_allow_html=True)

with col4:
    st.markdown(f"""
    <div class="metric-card amber">
        <div class="metric-icon">🧠</div>
        <div class="metric-value amber-text">60+</div>
        <div class="metric-label">Features Engineered</div>
        <div class="metric-delta positive">PySpark Pipeline</div>
    </div>
    """, unsafe_allow_html=True)

st.markdown("<br>", unsafe_allow_html=True)


# ============================================
# TAB LAYOUT
# ============================================

tab1, tab2, tab3, tab4, tab5 = st.tabs([
    "🔮 Predict Demand",
    "📊 EDA Insights",
    "📈 Model Performance",
    "🔍 Feature Insights",
    "ℹ️ About System"
])


# ============================================
# TAB 1: PREDICTION INTERFACE
# ============================================

with tab1:
    st.markdown("""
    <div class="section-header animate-fade-up">
        <div class="icon">🔮</div>
        <div class="text">
            <h2>Demand Prediction Engine</h2>
            <p>Enter recent sales data to generate an AI-powered demand forecast</p>
        </div>
    </div>
    """, unsafe_allow_html=True)

    pred_col1, spacer, pred_col2 = st.columns([5, 1, 5])

    with pred_col1:
        st.markdown("""
        <div class="glass-card">
            <h3 style="margin-top:0; color: #1a2332 !important;">
                📥 Input Parameters
            </h3>
        </div>
        """, unsafe_allow_html=True)

        input_col_a, input_col_b = st.columns(2)

        with input_col_a:
            yesterday_sales = st.number_input(
                "🔵 Yesterday's Sales",
                min_value=0, max_value=50000, value=4200, step=100,
                help="Units sold yesterday"
            )
            weekly_average = st.number_input(
                "🟢 7-Day Average",
                min_value=0, max_value=50000, value=4100, step=100,
                help="Average daily sales over the past week"
            )
            is_promotion = st.toggle("🏷️ Promotion Active", value=False)

        with input_col_b:
            last_week_sales = st.number_input(
                "🟡 Same Day Last Week",
                min_value=0, max_value=50000, value=4050, step=100,
                help="Sales on this same weekday last week"
            )
            day_of_week = st.selectbox(
                "📅 Day of Week",
                options=[
                    (2, "Monday"), (3, "Tuesday"), (4, "Wednesday"),
                    (5, "Thursday"), (6, "Friday"), (7, "Saturday"),
                    (1, "Sunday")
                ],
                format_func=lambda x: x[1],
                index=5
            )[0]
            is_holiday = st.toggle("🎄 Holiday", value=False)

        # Mini chart of input context
        st.markdown("<br>", unsafe_allow_html=True)

        input_context = pd.DataFrame({
            'Metric': ["Yesterday", "Last Week\nSame Day", "7-Day\nAverage"],
            'Units': [yesterday_sales, last_week_sales, weekly_average]
        })

        fig_context = px.bar(
            input_context, x='Metric', y='Units',
            title='📊 Input Sales Context',
            color='Units',
            color_continuous_scale=['#95d5b2', '#2d6a4f'],
            text='Units'
        )
        fig_context.update_traces(
            texttemplate='%{text:,.0f}',
            textposition='outside',
            marker_line_width=0
        )
        fig_context.update_layout(
            plot_bgcolor=CHART_BG,
            paper_bgcolor=CHART_BG,
            font=dict(color=CHART_FONT_COLOR, size=12, family='Inter'),
            showlegend=False,
            coloraxis_showscale=False,
            height=280,
            margin=dict(t=40, b=20, l=20, r=20),
            xaxis=dict(showgrid=False, color=CHART_FONT_COLOR),
            yaxis=dict(
                showgrid=True,
                gridcolor=CHART_GRID_COLOR,
                color=CHART_FONT_COLOR
            ),
            title_font_color=CHART_FONT_COLOR
        )
        st.plotly_chart(fig_context, use_container_width=True)

    with pred_col2:
        st.markdown("""
        <div class="glass-card">
            <h3 style="margin-top:0; color: #1a2332 !important;">
                📤 Forecast Result
            </h3>
        </div>
        """, unsafe_allow_html=True)

        if st.button(
            "🔮 Generate Forecast",
            type="primary",
            use_container_width=True
        ):
            # Progress animation
            progress_bar = st.progress(0)
            status_text = st.empty()

            steps = [
                "Loading model weights...",
                "Processing input features...",
                "Running inference...",
                "Calculating confidence intervals...",
                "Generating recommendation..."
            ]

            for i, step in enumerate(steps):
                status_text.markdown(
                    f"<p style='color: #6b7280 !important; "
                    f"font-size: 0.85rem;'>⏳ {step}</p>",
                    unsafe_allow_html=True
                )
                progress_bar.progress((i + 1) * 20)
                time.sleep(0.3)

            progress_bar.empty()
            status_text.empty()

            # Try calling the FastAPI backend
            prediction_success = False

            try:
                response = requests.post(
                    "http://127.0.0.1:8000/quick-predict",
                    json={
                        "yesterday_sales": yesterday_sales,
                        "last_week_same_day": last_week_sales,
                        "weekly_average": weekly_average,
                        "day_of_week": day_of_week,
                        "is_promotion": is_promotion,
                        "is_holiday": is_holiday
                    },
                    timeout=5
                )
                result = response.json()
                predicted = result['predicted_demand']
                recommendation = result['recommendation']
                confidence = result['confidence']
                note = result.get('note', '')
                prediction_success = True

            except requests.exceptions.ConnectionError:
                try:
                    from app.model import DemandForecaster
                    forecaster = DemandForecaster()
                    features = {
                        'sales_lag_1': yesterday_sales,
                        'sales_lag_7': last_week_sales,
                        'rolling_mean_7': weekly_average,
                        'day_of_week': day_of_week,
                        'is_weekend': 1 if day_of_week in [1, 7] else 0,
                        'onpromotion': 5 if is_promotion else 0,
                        'is_holiday': 1 if is_holiday else 0,
                    }
                    result = forecaster.predict(features)
                    predicted = result['predicted_demand']
                    recommendation = result['recommendation']
                    confidence = result['confidence']
                    note = "Direct model inference"
                    prediction_success = True
                except Exception:
                    weights = [0.5, 0.3, 0.2]
                    predicted = (
                        yesterday_sales * weights[0]
                        + last_week_sales * weights[1]
                        + weekly_average * weights[2]
                    )
                    if is_promotion:
                        predicted *= 1.15
                    if is_holiday:
                        predicted *= 0.85
                    if day_of_week in [1, 7]:
                        predicted *= 1.1
                    predicted = round(predicted)
                    recommendation = (
                        "Order stock to cover predicted demand "
                        "plus 10-15% safety buffer"
                    )
                    confidence = "Medium"
                    note = (
                        "Estimate (API offline — "
                        "weighted average fallback)"
                    )
                    prediction_success = True

            if prediction_success:
                st.markdown(f"""
                <div class="prediction-result animate-fade-up">
                    <div class="prediction-label">PREDICTED DEMAND</div>
                    <div class="prediction-value">{predicted:,.0f}</div>
                    <div class="prediction-units">units</div>
                </div>
                """, unsafe_allow_html=True)

                st.markdown("<br>", unsafe_allow_html=True)

                # Confidence gauge
                conf_map = {"High": 90, "Medium": 65, "Low": 40}
                conf_val = conf_map.get(confidence, 70)
                conf_color = (
                    "#2d6a4f" if conf_val >= 80
                    else "#d97706" if conf_val >= 60
                    else "#dc2626"
                )

                fig_gauge = go.Figure(go.Indicator(
                    mode="gauge+number",
                    value=conf_val,
                    number={
                        'suffix': '%',
                        'font': {'size': 28, 'color': CHART_FONT_COLOR}
                    },
                    title={
                        'text': 'Confidence',
                        'font': {'size': 14, 'color': '#6b7280'}
                    },
                    gauge={
                        'axis': {
                            'range': [0, 100],
                            'tickcolor': '#d1d5db'
                        },
                        'bar': {
                            'color': conf_color, 'thickness': 0.3
                        },
                        'bgcolor': 'rgba(45,106,79,0.06)',
                        'borderwidth': 0,
                        'steps': [
                            {
                                'range': [0, 40],
                                'color': 'rgba(220,38,38,0.06)'
                            },
                            {
                                'range': [40, 70],
                                'color': 'rgba(217,119,6,0.06)'
                            },
                            {
                                'range': [70, 100],
                                'color': 'rgba(45,106,79,0.06)'
                            }
                        ],
                        'threshold': {
                            'line': {'color': conf_color, 'width': 3},
                            'thickness': 0.8,
                            'value': conf_val
                        }
                    }
                ))
                fig_gauge.update_layout(
                    height=180,
                    margin=dict(t=30, b=0, l=30, r=30),
                    paper_bgcolor=CHART_BG,
                    font=dict(color=CHART_FONT_COLOR)
                )
                st.plotly_chart(fig_gauge, use_container_width=True)

                # Recommendation
                st.markdown(f"""
                <div class="insight-box success">
                    <h4>💡 Recommendation</h4>
                    <p>{recommendation}</p>
                </div>
                """, unsafe_allow_html=True)

                if note:
                    st.caption(f"ℹ️ {note}")

                # Comparison mini-chart
                pct_change = (
                    (predicted - yesterday_sales)
                    / yesterday_sales * 100
                )
                direction = "📈" if pct_change > 0 else "📉"

                st.markdown(f"""
                <div class="comparison-card">
                    <p class="label-text">Quick Comparison</p>
                    <p class="value-text">
                        {direction}
                        <strong>{abs(pct_change):.1f}%</strong>
                        {'above' if pct_change > 0 else 'below'}
                        yesterday's actual sales
                    </p>
                </div>
                """, unsafe_allow_html=True)
        else:
            st.markdown("""
            <div style="
                text-align: center;
                padding: 3rem;
                color: #9ca3af;
            ">
                <div style="font-size: 4rem; margin-bottom: 1rem;">
                    🔮
                </div>
                <p style="font-size: 1.1rem; color: #9ca3af !important;">
                    Enter your sales data and click<br>
                    <strong style="color: #2d6a4f !important;">
                        Generate Forecast
                    </strong> to see predictions
                </p>
            </div>
            """, unsafe_allow_html=True)

# ============================================
# TAB 2: EDA INSIGHTS
# ============================================

with tab2:
    st.markdown("""
    <div class="section-header animate-fade-up">
        <div class="icon">📊</div>
        <div class="text">
            <h2>Exploratory Data Analysis</h2>
            <p>Key patterns discovered from 3M+ retail transactions using BigQuery</p>
        </div>
    </div>
    """, unsafe_allow_html=True)

    # Path to EDA charts
    base_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    eda_dir = os.path.join(base_dir, 'results', 'eda')

    # Helper function to load and display chart with insight
    def show_eda_chart(filename, title, icon, insight_text, insight_type="default"):
        filepath = os.path.join(eda_dir, filename)
        if os.path.exists(filepath):
            st.markdown(f"""
            <div class="glass-card">
                <h3 style="margin-top:0;">{icon} {title}</h3>
            </div>
            """, unsafe_allow_html=True)
            st.image(filepath, use_container_width=True)

            box_class = "insight-box"
            if insight_type == "warning":
                box_class = "insight-box warning"
            elif insight_type == "success":
                box_class = "insight-box success"

            st.markdown(f"""
            <div class="{box_class}">
                <h4>💡 Business Insight</h4>
                <p>{insight_text}</p>
            </div>
            """, unsafe_allow_html=True)
            st.markdown("<br>", unsafe_allow_html=True)
        else:
            st.warning(f"Chart not found: {filename}")

    # EDA Category selector
    eda_view = st.radio(
        "Select Analysis View",
        ["All Charts", "Seasonality", "Promotions & Stores", "Data Quality"],
        horizontal=True
    )

    if eda_view in ["All Charts", "Seasonality"]:
        # Weekly Seasonality
        eda_col1, eda_col2 = st.columns(2)

        with eda_col1:
            show_eda_chart(
                "weekly_seasonality.png",
                "Weekly Demand Pattern",
                "📅",
                "Saturday sales are <strong>45% higher</strong> than Tuesday. "
                "Current ordering systems treat every day equally — this mismatch "
                "causes <strong>overstocking on weekdays</strong> and "
                "<strong>stockouts on weekends</strong>. Adjusting order quantities "
                "by day of week alone could save <strong>$80K annually</strong>."
            )

        with eda_col2:
            show_eda_chart(
                "monthly_seasonality.png",
                "Monthly Seasonality",
                "📆",
                "December demand is <strong>45% above annual average</strong> "
                "due to holiday shopping. January drops <strong>15% below average</strong> "
                "as consumers cut spending post-holidays. Stores must "
                "<strong>pre-position inventory by late November</strong> and "
                "<strong>reduce orders starting January 2nd</strong> to avoid waste.",
                "warning"
            )

        # Sales Trend
        show_eda_chart(
            "sales_trend.png",
            "Sales Trend Over Time (2013-2017)",
            "📈",
            "The retailer shows consistent <strong>~8% year-over-year growth</strong>. "
            "Without a trend feature in the model, predictions would systematically "
            "<strong>underestimate future demand</strong>. The <code>days_since_start</code> "
            "feature captures this upward trajectory.",
            "success"
        )

    if eda_view in ["All Charts", "Promotions & Stores"]:
        eda_col3, eda_col4 = st.columns(2)

        with eda_col3:
            show_eda_chart(
                "promotion_impact.png",
                "Promotion Effectiveness by Category",
                "🏷️",
                "Promotions lift <strong>GROCERY sales by 42%</strong> but "
                "<strong>DAIRY by only 8%</strong> and <strong>BABY CARE by 3%</strong>. "
                "The business is spending equal marketing budget across categories "
                "that respond very differently. <strong>Reallocating promotion spend</strong> "
                "from low-response to high-response categories could generate "
                "<strong>$200K+ in incremental revenue</strong> with zero additional spend.",
                "warning"
            )

        with eda_col4:
            show_eda_chart(
                "store_analysis.png",
                "Store Performance Comparison",
                "🏪",
                "Store Type A averages <strong>3.5x higher sales</strong> than Type D. "
                "Top 10 stores generate <strong>55% of total revenue</strong>. "
                "Forecasting errors at high-volume stores cost "
                "<strong>10x more</strong> than at small stores — ML deployment "
                "should prioritize these locations first.",
                "success"
            )

        # Category Sales
        show_eda_chart(
            "category_sales.png",
            "Total Sales by Product Category",
            "🛒",
            "Three categories — <strong>GROCERY, BEVERAGES, and PRODUCE</strong> — "
            "drive <strong>60% of all revenue</strong>. Improving demand forecasting "
            "for just these three covers the majority of the waste and stockout problem. "
            "12 of 33 categories have less than 1% share each — these are candidates "
            "for <strong>simple rule-based ordering</strong> instead of ML."
        )

    if eda_view in ["All Charts", "Data Quality"]:
        show_eda_chart(
            "zero_sales_analysis.png",
            "Data Sparsity by Category",
            "⚠️",
            "<strong>12 of 33 categories have >70% zero-sales days</strong>. "
            "Training ML models on these sparse categories would produce predictions "
            "that default to zero (correct 80% of the time but completely useless). "
            "These categories were <strong>excluded from ML automation</strong> and "
            "kept on manual ordering with minimum stock rules. "
            "<strong>Knowing what NOT to automate</strong> saved 3 months of "
            "engineering time and prevented deploying models that would perform "
            "worse than human judgment.",
            "warning"
        )

    # Summary stats
    st.markdown("<br>", unsafe_allow_html=True)
    st.markdown("""
    <div class="glass-card">
        <h3 style="margin-top:0;">📋 EDA Summary — Key Findings</h3>
    </div>
    """, unsafe_allow_html=True)

    summary_col1, summary_col2, summary_col3 = st.columns(3)

    with summary_col1:
        st.markdown("""
        <div class="metric-card emerald" style="text-align: left;">
            <div class="metric-icon">📅</div>
            <div class="metric-value emerald-text" style="font-size: 1.4rem;">45%</div>
            <div class="metric-label">Weekend Demand Surge</div>
            <p class="impact-desc">Saturday vs Tuesday — consistent across all years</p>
        </div>
        """, unsafe_allow_html=True)

    with summary_col2:
        st.markdown("""
        <div class="metric-card sky" style="text-align: left;">
            <div class="metric-icon">🏷️</div>
            <div class="metric-value sky-text" style="font-size: 1.4rem;">42% vs 3%</div>
            <div class="metric-label">Promotion Response Gap</div>
            <p class="impact-desc">GROCERY vs BABY CARE — budget reallocation opportunity</p>
        </div>
        """, unsafe_allow_html=True)

    with summary_col3:
        st.markdown("""
        <div class="metric-card amber" style="text-align: left;">
            <div class="metric-icon">🏪</div>
            <div class="metric-value amber-text" style="font-size: 1.4rem;">55%</div>
            <div class="metric-label">Revenue Concentration</div>
            <p class="impact-desc">Top 10 stores — prioritize ML deployment here</p>
        </div>
        """, unsafe_allow_html=True)

# ============================================
# MULTI-COLOR PALETTE (used across Tab 3 & 4)
# ============================================

MULTI_COLORS = [
    '#3b82f6',  # Blue
    '#8b5cf6',  # Purple
    '#f59e0b',  # Amber
    '#ef4444',  # Red
    '#14b8a6',  # Teal
    '#f97316',  # Orange
    '#6366f1',  # Indigo
    '#ec4899',  # Pink
    '#10b981',  # Emerald
    '#06b6d4',  # Cyan
    '#a855f7',  # Violet
    '#84cc16',  # Lime
    '#f43f5e',  # Rose
    '#0ea5e9',  # Sky
    '#d946ef',  # Fuchsia
]

GRADIENT_COLORSCALE = [
    [0.0, '#6366f1'],   # Indigo
    [0.25, '#3b82f6'],  # Blue
    [0.5, '#14b8a6'],   # Teal
    [0.75, '#f59e0b'],  # Amber
    [1.0, '#ef4444'],   # Red
]


# ============================================
# TAB 3: MODEL PERFORMANCE
# ============================================

with tab3:
    st.markdown("""
    <div class="section-header animate-fade-up">
        <div class="icon">📈</div>
        <div class="text">
            <h2>Model Performance Arena</h2>
            <p>Comparing 5 models across multiple accuracy metrics</p>
        </div>
    </div>
    """, unsafe_allow_html=True)

    selected_metric = st.radio(
        "Select Metric to Visualize",
        ["MAPE", "R²", "MAE", "RMSE"],
        horizontal=True,
        index=0
    )

    metric_configs = {
        "MAPE": {
            "title": "Forecast Error (MAPE %) — Lower is Better",
            "ascending": True,
            "format": ".1f",
            "suffix": "%",
        },
        "R²": {
            "title": "Variance Explained (R²) — Higher is Better",
            "ascending": False,
            "format": ".4f",
            "suffix": "",
        },
        "MAE": {
            "title": "Mean Absolute Error — Lower is Better",
            "ascending": True,
            "format": ".1f",
            "suffix": "",
        },
        "RMSE": {
            "title": "Root Mean Square Error — Lower is Better",
            "ascending": True,
            "format": ".1f",
            "suffix": "",
        },
    }

    config = metric_configs[selected_metric]

    perf_col1, perf_col2 = st.columns([3, 2])

    with perf_col1:
        sorted_df = results_df.sort_values(
            selected_metric, ascending=config['ascending']
        )

        # --- Multi-color bars (one color per model) ---
        model_colors = {
            'Baseline (7-Day MA)': '#94a3b8',   # Slate grey
            'Linear Regression':   '#f59e0b',   # Amber
            'Random Forest':       '#8b5cf6',   # Purple
            'XGBoost':             '#3b82f6',   # Blue
            'LightGBM':           '#10b981',   # Emerald
        }

        bar_colors = [
            model_colors.get(m, '#6b7280')
            for m in sorted_df['Model']
        ]

        fig_metric = go.Figure()
        fig_metric.add_trace(go.Bar(
            y=sorted_df['Model'],
            x=sorted_df[selected_metric],
            orientation='h',
            marker=dict(
                color=bar_colors,
                line=dict(width=0),
                cornerradius=6
            ),
            text=[
                f"{v:{config['format']}}{config['suffix']}"
                for v in sorted_df[selected_metric]
            ],
            textposition='outside',
            textfont=dict(
                size=14, color=CHART_FONT_COLOR, family='Inter'
            )
        ))

        fig_metric.update_layout(
            title=dict(
                text=config['title'],
                font=dict(size=16, color=CHART_FONT_COLOR)
            ),
            plot_bgcolor=CHART_BG,
            paper_bgcolor=CHART_BG,
            font=dict(
                color=CHART_FONT_COLOR, family='Inter'
            ),
            height=400,
            margin=dict(t=60, b=20, l=20, r=80),
            xaxis=dict(
                showgrid=True,
                gridcolor=CHART_GRID_COLOR,
                zeroline=False,
                color=CHART_FONT_COLOR
            ),
            yaxis=dict(
                showgrid=False, color=CHART_FONT_COLOR
            )
        )

        if show_annotations:
            best_model = sorted_df.iloc[0]['Model']
            best_val = sorted_df.iloc[0][selected_metric]
            best_color = model_colors.get(best_model, '#2d6a4f')
            fig_metric.add_annotation(
                x=best_val, y=best_model,
                text="⭐ BEST",
                showarrow=True, arrowhead=2,
                arrowcolor=best_color,
                font=dict(size=12, color=best_color),
                ax=50, ay=-30
            )

        st.plotly_chart(fig_metric, use_container_width=True)

    with perf_col2:
        # --- Radar chart with distinct model colors ---
        categories = ['MAE', 'RMSE', 'MAPE', 'R²']

        radar_colors = [
            '#94a3b8',  # Baseline - Slate
            '#f59e0b',  # Linear Regression - Amber
            '#8b5cf6',  # Random Forest - Purple
            '#3b82f6',  # XGBoost - Blue
            '#10b981',  # LightGBM - Emerald
        ]

        fig_radar = go.Figure()

        for i, model in enumerate(results_df['Model']):
            values = []
            for cat in categories:
                v = results_df.loc[
                    results_df['Model'] == model, cat
                ].values[0]
                col_min = results_df[cat].min()
                col_max = results_df[cat].max()
                rng = (col_max - col_min) if col_max != col_min else 1
                if cat == 'R²':
                    values.append((v - col_min) / rng)
                else:
                    values.append(1 - (v - col_min) / rng)
            values.append(values[0])

            color = radar_colors[i % len(radar_colors)]
            # Parse hex to rgba
            r_val = int(color[1:3], 16)
            g_val = int(color[3:5], 16)
            b_val = int(color[5:7], 16)

            fig_radar.add_trace(go.Scatterpolar(
                r=values,
                theta=categories + [categories[0]],
                name=model,
                line=dict(color=color, width=2.5),
                fill='toself',
                fillcolor=f"rgba({r_val}, {g_val}, {b_val}, 0.08)"
            ))

        fig_radar.update_layout(
            polar=dict(
                bgcolor=CHART_BG,
                radialaxis=dict(
                    visible=True, range=[0, 1],
                    showticklabels=False,
                    gridcolor=CHART_GRID_COLOR
                ),
                angularaxis=dict(
                    gridcolor=CHART_GRID_COLOR,
                    linecolor=CHART_GRID_COLOR,
                    tickfont=dict(color=CHART_FONT_COLOR)
                )
            ),
            paper_bgcolor=CHART_BG,
            font=dict(color=CHART_FONT_COLOR, family='Inter'),
            title=dict(
                text='Model Comparison Radar',
                font=dict(size=16, color=CHART_FONT_COLOR)
            ),
            height=400,
            margin=dict(t=60, b=20),
            legend=dict(
                font=dict(size=10, color=CHART_FONT_COLOR),
                bgcolor=CHART_BG
            )
        )
        st.plotly_chart(fig_radar, use_container_width=True)

    # Detailed comparison table
    st.markdown("<br>", unsafe_allow_html=True)
    st.markdown("""
    <div class="section-header">
        <div class="icon" style="
            background: linear-gradient(135deg, #3b82f6, #8b5cf6);
        ">📋</div>
        <div class="text">
            <h2>Detailed Metrics Table</h2>
            <p>Complete performance breakdown for all models</p>
        </div>
    </div>
    """, unsafe_allow_html=True)

    styled_df = results_df.copy()
    styled_df['Improvement'] = styled_df['MAPE'].apply(
        lambda x: (
            f"🟢 {(results_df['MAPE'].max() - x) / results_df['MAPE'].max() * 100:.1f}%"
            if x != results_df['MAPE'].max() else "— Baseline"
        )
    )

    table_html = '<table class="comparison-table"><thead><tr>'
    for col in styled_df.columns:
        table_html += f'<th>{col}</th>'
    table_html += '</tr></thead><tbody>'
    for _, row in styled_df.iterrows():
        table_html += '<tr>'
        for col in styled_df.columns:
            val = row[col]
            if isinstance(val, float):
                val = (
                    f"{val:.4f}" if col == 'R²' else f"{val:.1f}"
                )
            table_html += f'<td>{val}</td>'
        table_html += '</tr>'
    table_html += '</tbody></table>'

    st.markdown(table_html, unsafe_allow_html=True)

    st.markdown("<br>", unsafe_allow_html=True)
    csv_data = results_df.to_csv(index=False)
    st.download_button(
        label="📥 Download Results as CSV",
        data=csv_data,
        file_name="model_comparison_results.csv",
        mime="text/csv"
    )

    # Business impact section
    st.markdown("<br>", unsafe_allow_html=True)
    st.markdown("""
    <div class="section-header">
        <div class="icon" style="
            background: linear-gradient(135deg, #f59e0b, #f97316);
        ">💰</div>
        <div class="text">
            <h2>Business Impact</h2>
            <p>Translating model accuracy into real-world value</p>
        </div>
    </div>
    """, unsafe_allow_html=True)

    impact_col1, impact_col2, impact_col3 = st.columns(3)

    with impact_col1:
        st.markdown("""
        <div class="metric-card emerald" style="text-align: left;">
            <div style="display: flex; align-items: center; gap: 0.8rem;">
                <div style="
                    font-size: 2rem;
                    background: linear-gradient(135deg, #3b82f6, #6366f1);
                    width: 50px; height: 50px; border-radius: 12px;
                    display: flex; align-items: center;
                    justify-content: center;
                ">📉</div>
                <div>
                    <div class="metric-value emerald-text"
                         style="font-size: 1.6rem;">64.4%</div>
                    <div class="metric-label">Error Reduction</div>
                </div>
            </div>
            <p class="impact-desc">
                vs moving average baseline across all product categories
            </p>
        </div>
        """, unsafe_allow_html=True)

    with impact_col2:
        st.markdown("""
        <div class="metric-card sky" style="text-align: left;">
            <div style="display: flex; align-items: center; gap: 0.8rem;">
                <div style="
                    font-size: 2rem;
                    background: linear-gradient(135deg, #8b5cf6, #a855f7);
                    width: 50px; height: 50px; border-radius: 12px;
                    display: flex; align-items: center;
                    justify-content: center;
                ">🗑️</div>
                <div>
                    <div class="metric-value sky-text"
                         style="font-size: 1.6rem;">$192K</div>
                    <div class="metric-label">Waste Reduction</div>
                </div>
            </div>
            <p class="impact-desc">
                Annual savings from reduced food waste across 10 stores
            </p>
        </div>
        """, unsafe_allow_html=True)

    with impact_col3:
        st.markdown("""
        <div class="metric-card amber" style="text-align: left;">
            <div style="display: flex; align-items: center; gap: 0.8rem;">
                <div style="
                    font-size: 2rem;
                    background: linear-gradient(135deg, #f59e0b, #f97316);
                    width: 50px; height: 50px; border-radius: 12px;
                    display: flex; align-items: center;
                    justify-content: center;
                ">📣</div>
                <div>
                    <div class="metric-value amber-text"
                         style="font-size: 1.6rem;">$200K+</div>
                    <div class="metric-label">Marketing Savings</div>
                </div>
            </div>
            <p class="impact-desc">
                Identified misallocated spend via demand pattern analysis
            </p>
        </div>
        """, unsafe_allow_html=True)


# ============================================
# TAB 4: FEATURE IMPORTANCE
# ============================================

with tab4:
    st.markdown("""
    <div class="section-header animate-fade-up">
        <div class="icon">🔍</div>
        <div class="text">
            <h2>What Drives Predictions?</h2>
            <p>Understanding which features the model relies on most</p>
        </div>
    </div>
    """, unsafe_allow_html=True)

    if importance_df is not None:
        if 'Importance_Pct' not in importance_df.columns:
            importance_df['Importance_Pct'] = (
                importance_df['Importance']
                / importance_df['Importance'].sum() * 100
            )

        ctrl_col1, ctrl_col2 = st.columns([1, 1])
        with ctrl_col1:
            top_n = st.slider(
                "Number of features to display",
                min_value=5,
                max_value=min(30, len(importance_df)),
                value=15, step=1
            )
        with ctrl_col2:
            chart_type = st.radio(
                "Chart Style",
                ["Horizontal Bar", "Lollipop", "Treemap"],
                horizontal=True
            )

        top_features = importance_df.head(top_n).copy()
        y_col = (
            'Business Meaning'
            if 'Business Meaning' in top_features.columns
            else 'Feature'
        )

        if chart_type == "Horizontal Bar":
            sorted_feats = top_features.sort_values(
                'Importance_Pct', ascending=True
            )

            # --- Multi-color bars by rank ---
            n_feats = len(sorted_feats)
            bar_colors_feat = [
                MULTI_COLORS[i % len(MULTI_COLORS)]
                for i in range(n_feats)
            ]

            fig_imp = go.Figure()
            fig_imp.add_trace(go.Bar(
                y=sorted_feats[y_col],
                x=sorted_feats['Importance_Pct'],
                orientation='h',
                marker=dict(
                    color=bar_colors_feat,
                    line=dict(width=0),
                    cornerradius=4
                ),
                text=[
                    f"{v:.1f}%"
                    for v in sorted_feats['Importance_Pct']
                ],
                textposition='outside',
                textfont=dict(
                    color=CHART_FONT_COLOR, size=11,
                    family='Inter'
                )
            ))

            fig_imp.update_layout(
                title=dict(
                    text=f'Top {top_n} Features by Importance',
                    font=dict(size=16, color=CHART_FONT_COLOR)
                ),
                plot_bgcolor=CHART_BG,
                paper_bgcolor=CHART_BG,
                font=dict(
                    color=CHART_FONT_COLOR, family='Inter'
                ),
                height=max(400, top_n * 35),
                margin=dict(t=60, b=20, l=20, r=80),
                xaxis=dict(
                    showgrid=True,
                    gridcolor=CHART_GRID_COLOR,
                    zeroline=False,
                    title='Importance (%)',
                    color=CHART_FONT_COLOR
                ),
                yaxis=dict(
                    showgrid=False, color=CHART_FONT_COLOR
                )
            )
            st.plotly_chart(fig_imp, use_container_width=True)

        elif chart_type == "Lollipop":
            sorted_feats = top_features.sort_values(
                'Importance_Pct', ascending=True
            )
            fig_lollipop = go.Figure()

            n_feats = len(sorted_feats)

            # --- Multi-color lollipop stems ---
            for idx, (_, row) in enumerate(sorted_feats.iterrows()):
                color = MULTI_COLORS[idx % len(MULTI_COLORS)]
                fig_lollipop.add_trace(go.Scatter(
                    x=[0, row['Importance_Pct']],
                    y=[row[y_col], row[y_col]],
                    mode='lines',
                    line=dict(color=color, width=2.5),
                    opacity=0.5,
                    showlegend=False
                ))

            # --- Multi-color dots ---
            dot_colors = [
                MULTI_COLORS[i % len(MULTI_COLORS)]
                for i in range(n_feats)
            ]

            fig_lollipop.add_trace(go.Scatter(
                x=sorted_feats['Importance_Pct'],
                y=sorted_feats[y_col],
                mode='markers+text',
                marker=dict(
                    size=14,
                    color=dot_colors,
                    line=dict(width=2, color='#ffffff')
                ),
                text=[
                    f" {v:.1f}%"
                    for v in sorted_feats['Importance_Pct']
                ],
                textposition='middle right',
                textfont=dict(
                    color=CHART_FONT_COLOR, size=11
                ),
                showlegend=False
            ))

            fig_lollipop.update_layout(
                title=dict(
                    text=f'Top {top_n} Features — Lollipop Chart',
                    font=dict(size=16, color=CHART_FONT_COLOR)
                ),
                plot_bgcolor=CHART_BG,
                paper_bgcolor=CHART_BG,
                font=dict(
                    color=CHART_FONT_COLOR, family='Inter'
                ),
                height=max(400, top_n * 35),
                margin=dict(t=60, b=20, l=20, r=80),
                xaxis=dict(
                    showgrid=True,
                    gridcolor=CHART_GRID_COLOR,
                    zeroline=False,
                    title='Importance (%)',
                    color=CHART_FONT_COLOR
                ),
                yaxis=dict(
                    showgrid=False, color=CHART_FONT_COLOR
                )
            )
            st.plotly_chart(fig_lollipop, use_container_width=True)

        else:  # Treemap
            fig_tree = px.treemap(
                top_features,
                path=[y_col],
                values='Importance_Pct',
                color='Importance_Pct',
                color_continuous_scale=[
                    '#6366f1', '#3b82f6', '#14b8a6',
                    '#f59e0b', '#ef4444'
                ],
                title=f'Feature Importance Treemap — Top {top_n}'
            )
            fig_tree.update_layout(
                paper_bgcolor=CHART_BG,
                font=dict(
                    color=CHART_FONT_COLOR, family='Inter'
                ),
                height=500,
                coloraxis_showscale=False,
                margin=dict(t=50, b=20, l=20, r=20),
                title_font_color=CHART_FONT_COLOR
            )
            fig_tree.update_traces(
                textinfo='label+percent root',
                textfont=dict(size=13)
            )
            st.plotly_chart(fig_tree, use_container_width=True)

        # Feature category breakdown
        st.markdown("<br>", unsafe_allow_html=True)

        cat_col1, cat_col2 = st.columns(2)

        with cat_col1:
            categories = {
                'Sales History': [
                    'sales_lag_1', 'sales_lag_7',
                    'sales_lag_14', 'sales_lag_28'
                ],
                'Rolling Stats': [
                    'rolling_mean_7', 'rolling_mean_30',
                    'rolling_std_7', 'rolling_std_14',
                    'rolling_max_7', 'rolling_max_14'
                ],
                'Cross-Store': [
                    'category_avg_all_stores'
                ],
                'Cumulative': [
                    'expanding_mean', 'expanding_std'
                ],
                'Calendar & Segment': [
                    'day_of_month', 'cluster'
                ],
            }

            cat_importance = {}
            for cat, feats in categories.items():
                mask = importance_df['Feature'].isin(feats)
                cat_importance[cat] = importance_df.loc[
                    mask, 'Importance_Pct'
                ].sum()

            cat_df = pd.DataFrame(
                list(cat_importance.items()),
                columns=['Category', 'Importance']
            )

            # --- Multi-color donut ---
            donut_colors = [
                '#3b82f6',  # Blue - Sales History
                '#8b5cf6',  # Purple - Rolling Stats
                '#f59e0b',  # Amber - Cross-Store
                '#14b8a6',  # Teal - Cumulative
                '#f43f5e',  # Rose - Calendar & Segment
            ]

            fig_donut = go.Figure(data=[go.Pie(
                labels=cat_df['Category'],
                values=cat_df['Importance'],
                hole=0.6,
                marker=dict(
                    colors=donut_colors[:len(cat_df)],
                    line=dict(color='#ffffff', width=3)
                ),
                textinfo='label+percent',
                textfont=dict(size=12, color=CHART_FONT_COLOR),
                hovertemplate=(
                    '<b>%{label}</b><br>'
                    'Importance: %{value:.1f}%<br>'
                    '<extra></extra>'
                )
            )])

            fig_donut.update_layout(
                title=dict(
                    text='Feature Category Breakdown',
                    font=dict(size=16, color=CHART_FONT_COLOR)
                ),
                paper_bgcolor=CHART_BG,
                plot_bgcolor=CHART_BG,
                font=dict(
                    color=CHART_FONT_COLOR, family='Inter'
                ),
                height=350,
                margin=dict(t=50, b=20),
                showlegend=True,
                legend=dict(
                    bgcolor=CHART_BG,
                    font=dict(size=11, color=CHART_FONT_COLOR)
                ),
                annotations=[dict(
                    text='Features',
                    x=0.5, y=0.5,
                    font_size=14,
                    showarrow=False,
                    font_color='#9ca3af'
                )]
            )
            st.plotly_chart(fig_donut, use_container_width=True)

        with cat_col2:
            st.markdown("""
            <div class="insight-box" style="margin-top: 1rem;">
                <h4>🔑 Key Insight</h4>
                <p>
                    <strong>Short-term sales momentum dominates forecasting.</strong>
                    The 7-day rolling average and same-day-last-week sales
                    together drive <strong>82.1% of prediction accuracy</strong>.
                    This means the model primarily learns from
                    <em>"what sold recently"</em> and <em>"what sold on
                    this same weekday"</em> — confirming that demand
                    follows strong weekly cyclical patterns rather than
                    long-term trends or store-level characteristics.
                </p>
            </div>
            """, unsafe_allow_html=True)

            st.markdown("""
            <div class="insight-box warning" style="margin-top: 1rem;">
                <h4>⚠️ Data Freshness Is Critical</h4>
                <p>
                    Recent sales history (all lag values + rolling
                    statistics) accounts for <strong>86.6% of forecast
                    accuracy</strong>. A single day of missing or delayed
                    POS data corrupts the 7-day average — your
                    <em>most powerful feature</em> (49.9%). Ensure the
                    daily sales pipeline completes
                    <strong>before morning replenishment decisions</strong>.
                    Late data doesn't just reduce accuracy — it
                    <strong>collapses the model's primary signal</strong>.
                </p>
            </div>
            """, unsafe_allow_html=True)

            st.markdown("""
            <div class="insight-box success" style="margin-top: 1rem;">
                <h4>✅ Actionable Takeaway</h4>
                <p>
                    <strong>Cross-store category benchmarking is your
                    third strongest lever</strong> — category average
                    across all stores contributes <strong>10.6%</strong>
                    to accuracy. Use this to detect underperforming
                    locations (stores consistently below category
                    average signal a local issue, not a demand problem).
                    For <strong>new store launches or cold-start
                    scenarios</strong> where no sales history exists,
                    category averages become your primary forecasting
                    input until 7+ days of local data accumulate.
                    Store cluster and calendar effects contribute
                    under 1% — avoid over-engineering rules around
                    month-start ordering or store-type heuristics.
                </p>
            </div>
            """, unsafe_allow_html=True)
    else:
        st.warning(
            "Feature importance data not found. "
            "Run model training notebook first."
        )

# ============================================
# TAB 5: ABOUT
# ============================================

with tab5:
    st.markdown("""
    <div class="section-header animate-fade-up">
        <div class="icon">ℹ️</div>
        <div class="text">
            <h2>About This System</h2>
            <p>Architecture, methodology, and key results</p>
        </div>
    </div>
    """, unsafe_allow_html=True)

    # Problem statement
    st.markdown("""
    <div class="problem-card animate-fade-up">
        <h3>🎯 Problem Statement</h3>
        <p>
            Multi-location retail operations lose
            <strong class="highlight-red">8-15% of revenue</strong>
            to food waste from inaccurate demand forecasting.
            This system uses machine learning to predict daily
            item-level demand, enabling optimized inventory
            ordering and reducing waste significantly.
        </p>
    </div>
    """, unsafe_allow_html=True)

    st.markdown("<br>", unsafe_allow_html=True)

    # Architecture diagram
    st.markdown("### 🏗️ Technical Architecture")

    arch_cols = st.columns([2, 1, 2, 1, 2, 1, 2, 1, 2])

    arch_steps = [
        ("🗄️", "BigQuery", "Data Storage\n& SQL EDA"),
        ("➡️", "", ""),
        ("⚡", "PySpark", "Feature Engineering\n60+ features"),
        ("➡️", "", ""),
        ("🤖", "XGBoost", "ML Model\n9.42% MAPE"),
        ("➡️", "", ""),
        ("🚀", "FastAPI", "Prediction API\nREST endpoints"),
        ("➡️", "", ""),
        ("📊", "Streamlit", "Dashboard\nVisualization"),
    ]

    for i, (icon, title, desc) in enumerate(arch_steps):
        with arch_cols[i]:
            if title:
                st.markdown(f"""
                <div class="arch-step">
                    <div class="arch-icon">{icon}</div>
                    <div class="arch-title">{title}</div>
                    <div class="arch-desc">{desc}</div>
                </div>
                """, unsafe_allow_html=True)
            else:
                st.markdown(f"""
                <div class="arch-arrow">{icon}</div>
                """, unsafe_allow_html=True)

    st.markdown("<br>", unsafe_allow_html=True)

    # Key results
    st.markdown("### 📊 Key Results")

    results_cards = st.columns(3)

    results_data = [
        ("🏆", "Best Model", "XGBoost", "emerald"),
        ("🎯", "MAPE", "9.42%", "teal"),
        ("📈", "Improvement", "64.4%", "sky"),
        ("💰", "Annual Savings", "$192,000", "amber"),
        ("🧠", "Features", "60+", "emerald"),
        ("🔬", "Models Tested", "5", "teal"),
    ]

    for i, (icon, label, value, color) in enumerate(results_data):
        with results_cards[i % 3]:
            st.markdown(f"""
            <div class="metric-card {color}"
                 style="margin-bottom: 1rem;">
                <div class="metric-icon">{icon}</div>
                <div class="metric-value {color}-text"
                     style="font-size: 1.5rem;">{value}</div>
                <div class="metric-label">{label}</div>
            </div>
            """, unsafe_allow_html=True)

    st.markdown("<br>", unsafe_allow_html=True)

    # Tech stack pills
    st.markdown("### 🛠️ Technology Stack")
    st.markdown("""
    <div style="margin: 1rem 0;">
        <span class="stat-pill">Python</span>
        <span class="stat-pill">BigQuery</span>
        <span class="stat-pill">PySpark</span>
        <span class="stat-pill">XGBoost</span>
        <span class="stat-pill">LightGBM</span>
        <span class="stat-pill">scikit-learn</span>
        <span class="stat-pill">FastAPI</span>
        <span class="stat-pill">Streamlit</span>
        <span class="stat-pill">Plotly</span>
        <span class="stat-pill">Docker</span>
        <span class="stat-pill">Pandas</span>
        <span class="stat-pill">NumPy</span>
    </div>
    """, unsafe_allow_html=True)

    st.markdown("<br>", unsafe_allow_html=True)

    # About the builder
    st.markdown("""
    <div class="profile-card">
        <div style="
            display: flex; align-items: center; gap: 1.5rem;
        ">
            <div style="
                width: 70px; height: 70px; border-radius: 50%;
                background: linear-gradient(135deg, #2d6a4f, #52b788);
                display: flex; align-items: center;
                justify-content: center;
                font-size: 2rem; flex-shrink: 0;
            ">👨‍💻</div>
            <div>
                <h3>Anush Kundu</h3>
                <p class="subtitle">Data Scientist </p>
                <p class="edu">
                    MSc Data Science, Kingston University London | 2.5 years experience | Retail & Commercial Analytics |
                </p>
                <div style="margin-top: 0.8rem;">
                    <a href="https://linkedin.com/in/anushkundu"
                       target="_blank">🔗 LinkedIn</a>
                    <span style="margin: 0 0.5rem; color: #d1d5db;">
                        |
                    </span>
                    <a href="https://github.com/anushkundu"
                       target="_blank">🐙 GitHub</a>
                </div>
            </div>
        </div>
    </div>
    """, unsafe_allow_html=True)


# ============================================
# FOOTER
# ============================================

st.markdown("""
<div class="custom-footer">
    <p style="
        font-size: 0.9rem;
        color: #4a5568 !important;
        margin-bottom: 0.5rem;
    ">
        📊 DemandCast AI — Demand Forecasting System v1.0
    </p>
    <p>
        Built with BigQuery · PySpark · LightGBM ·
        FastAPI · Streamlit · Docker
    </p>
    <div class="footer-links" style="margin-top: 0.8rem;">
        <a href="https://github.com/anushkundu">GitHub</a> ·
        <a href="https://linkedin.com/in/anushkundu">LinkedIn</a>
    </div>
    <p style="
        margin-top: 0.8rem;
        font-size: 0.75rem;
        color: #9ca3af !important;
    ">
        © 2024 Anush Kundu. All rights reserved.
    </p>
</div>
""", unsafe_allow_html=True)