# -*- coding: utf-8 -*-
"""main.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/125nQmCbYYke2khbfhXGHaz4lJU3n6GOL
"""

# ============================================
# File: app/main.py
#
# The main FastAPI application.
# This is what runs when you start the server.
# ============================================

from fastapi import FastAPI, HTTPException
from pydantic import BaseModel, Field
from typing import Optional
from app.model import DemandForecaster

# ============================================
# Initialize FastAPI app
# ============================================

app = FastAPI(
    title="Demand Forecasting API",
    description="""
    Predict daily item-level demand for retail store operations.

    Built with LightGBM trained on 3M+ retail transactions.
    Achieves 19.5% MAPE — 49% better than moving average baseline.

    **Business Impact:** Estimated $127K annual waste reduction.
    """,
    version="1.0.0",
    contact={
        "name": "Anush Kundu",
        "email": "anushkundu55@gmail.com"
    }
)

# ============================================
# Load model at startup (runs once)
# ============================================

forecaster = DemandForecaster()

# ============================================
# Define request/response schemas
#
# Pydantic models validate input automatically.
# If someone sends bad data, they get a clear error.
# ============================================

class ForecastRequest(BaseModel):
    """Input features for a demand prediction."""

    # Required features (most important ones)
    sales_lag_1: float = Field(..., description="Yesterday's sales", example=4200)
    sales_lag_7: float = Field(..., description="Same day last week sales", example=4050)
    rolling_mean_7: float = Field(..., description="7-day average sales", example=4100)
    day_of_week: int = Field(..., description="Day of week (1=Sun, 7=Sat)", ge=1, le=7, example=7)
    month: int = Field(..., description="Month (1-12)", ge=1, le=12, example=3)
    onpromotion: int = Field(..., description="Number of items on promotion", ge=0, example=5)

    # Optional features (improve accuracy if provided)
    sales_lag_14: Optional[float] = Field(None, description="Sales 2 weeks ago")
    sales_lag_28: Optional[float] = Field(None, description="Sales 4 weeks ago")
    rolling_mean_14: Optional[float] = Field(None, description="14-day average sales")
    rolling_mean_30: Optional[float] = Field(None, description="30-day average sales")
    rolling_std_7: Optional[float] = Field(None, description="7-day sales volatility")
    rolling_std_14: Optional[float] = Field(None, description="14-day sales volatility")
    rolling_std_30: Optional[float] = Field(None, description="30-day sales volatility")
    is_weekend: Optional[int] = Field(None, description="1 if weekend, 0 if weekday")
    is_holiday: Optional[int] = Field(None, description="1 if holiday, 0 otherwise")
    is_december: Optional[int] = Field(None, description="1 if December, 0 otherwise")
    is_month_start: Optional[int] = Field(None, description="1 if first 5 days of month")
    is_month_end: Optional[int] = Field(None, description="1 if last 5 days of month")
    oil_price: Optional[float] = Field(None, description="Current oil price (USD)")
    days_until_next_holiday: Optional[int] = Field(None, description="Days until next holiday")
    promo_days_last_7: Optional[int] = Field(None, description="Promotion days in last 7 days")
    store_type_encoded: Optional[int] = Field(None, description="Store type (1-5, 5=largest)")
    family_encoded: Optional[int] = Field(None, description="Product category code")
    expanding_mean: Optional[float] = Field(None, description="Long-term average sales")
    year: Optional[int] = Field(None, description="Year", example=2025)
    quarter: Optional[int] = Field(None, description="Quarter (1-4)")
    day_of_month: Optional[int] = Field(None, description="Day of month (1-31)")
    week_of_year: Optional[int] = Field(None, description="Week number (1-52)")

    class Config:
        json_schema_extra = {
            "example": {
                "sales_lag_1": 4200,
                "sales_lag_7": 4050,
                "rolling_mean_7": 4100,
                "day_of_week": 7,
                "month": 3,
                "onpromotion": 5,
                "is_weekend": 1,
                "is_holiday": 0,
                "oil_price": 52.3,
                "store_type_encoded": 4,
                "family_encoded": 0
            }
        }


class QuickForecastRequest(BaseModel):
    """Simplified input — just the essentials for a quick prediction."""

    yesterday_sales: float = Field(..., description="How much did you sell yesterday?", example=4200)
    last_week_same_day: float = Field(..., description="Sales on this day last week?", example=4050)
    weekly_average: float = Field(..., description="Average daily sales this past week?", example=4100)
    day_of_week: int = Field(..., description="1=Sun, 2=Mon, ... 7=Sat", example=7)
    is_promotion: bool = Field(False, description="Is there a promotion today?")
    is_holiday: bool = Field(False, description="Is it a holiday?")


# ============================================
# API ENDPOINTS
# ============================================

@app.get("/")
def home():
    """Health check — confirms API is running."""
    return {
        "service": "Demand Forecasting API",
        "status": "running",
        "model": "LightGBM (19.5% MAPE)",
        "version": "1.0.0",
        "endpoints": {
            "/predict": "Full prediction with all features (POST)",
            "/quick-predict": "Quick prediction with minimal inputs (POST)",
            "/model-info": "Model performance and feature details (GET)",
            "/docs": "Interactive API documentation (GET)"
        }
    }


@app.get("/health")
def health_check():
    """Detailed health check for monitoring systems."""
    return {
        "status": "healthy",
        "model_loaded": forecaster.model is not None,
        "features_count": len(forecaster.feature_columns)
    }


@app.post("/predict")
def predict(request: ForecastRequest):
    """
    Full prediction with detailed features.

    Send as many features as available — the more features
    provided, the more accurate the prediction.

    Returns predicted demand, confidence level, and
    ordering recommendation.
    """

    # Convert request to dictionary, removing None values
    features = {k: v for k, v in request.dict().items() if v is not None}

    # Auto-calculate derived features if not provided
    if 'is_weekend' not in features:
        features['is_weekend'] = 1 if features.get('day_of_week', 0) in [1, 7] else 0

    if 'is_december' not in features:
        features['is_december'] = 1 if features.get('month', 0) == 12 else 0

    if 'quarter' not in features and 'month' in features:
        features['quarter'] = (features['month'] - 1) // 3 + 1

    # Calculate momentum if we have the data
    if 'rolling_mean_7' in features and 'rolling_mean_14' in features:
        rm7 = features['rolling_mean_7']
        rm14 = features['rolling_mean_14']
        features['momentum_7_14'] = round((rm7 - rm14) / (rm14 + 1), 4)

    # Calculate week-over-week change
    if 'sales_lag_1' in features and 'sales_lag_7' in features:
        sl1 = features['sales_lag_1']
        sl7 = features['sales_lag_7']
        features['wow_change'] = round((sl1 - sl7) / (sl7 + 1), 4)

    try:
        result = forecaster.predict(features)
        return result
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Prediction error: {str(e)}")


@app.post("/quick-predict")
def quick_predict(request: QuickForecastRequest):
    """
    Simplified prediction — just answer 4-5 simple questions.

    Designed for store managers who don't know feature names.
    Just provide yesterday's sales, last week's sales, and
    basic context.
    """

    # Translate simple inputs to model features
    features = {
        'sales_lag_1': request.yesterday_sales,
        'sales_lag_7': request.last_week_same_day,
        'rolling_mean_7': request.weekly_average,
        'day_of_week': request.day_of_week,
        'is_weekend': 1 if request.day_of_week in [1, 7] else 0,
        'onpromotion': 5 if request.is_promotion else 0,
        'is_holiday': 1 if request.is_holiday else 0,
        'month': 1,  # Default, would be auto-detected in production
    }

    try:
        result = forecaster.predict(features)

        # Simplify the response for non-technical users
        return {
            "predicted_demand": result["predicted_demand"],
            "recommendation": result["recommendation"],
            "confidence": result["confidence"],
            "note": f"Based on {result['features_provided']} of {result['features_expected']} features. Provide more features via /predict for higher accuracy."
        }
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Prediction error: {str(e)}")


@app.get("/model-info")
def model_info():
    """
    Returns model performance metrics, feature list,
    and business impact estimates.

    Useful for stakeholders evaluating the model.
    """
    return forecaster.get_model_info()


@app.get("/feature-list")
def feature_list():
    """Returns the list of all features the model uses."""
    return {
        "total_features": len(forecaster.feature_columns),
        "features": forecaster.feature_columns,
        "required_for_quick_predict": [
            "yesterday_sales",
            "last_week_same_day",
            "weekly_average",
            "day_of_week"
        ],
        "recommended_for_full_predict": [
            "sales_lag_1", "sales_lag_7", "rolling_mean_7",
            "day_of_week", "month", "onpromotion",
            "is_weekend", "is_holiday", "oil_price",
            "store_type_encoded", "family_encoded"
        ]
    }