# -*- coding: utf-8 -*-
"""model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/125nQmCbYYke2khbfhXGHaz4lJU3n6GOL
"""

# ============================================
# File: app/model.py
#
# This file handles loading the trained model
# and making predictions.
#
# Separated from main.py for clean code structure.
# ============================================

import pickle
import json
import numpy as np
import pandas as pd
import os

class DemandForecaster:
    """
    Loads the trained LightGBM model and makes predictions.

    WHY A CLASS?
    - Loads model ONCE when server starts (not every request)
    - Keeps model in memory for fast predictions
    - Clean interface: forecaster.predict(features)
    """

    def __init__(self):
        """Load model and feature list on initialization."""

        # Find the models directory
        # Works whether run from project root or app/ folder
        base_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
        models_dir = os.path.join(base_dir, 'models')

        # Load trained LightGBM model
        model_path = os.path.join(models_dir, 'best_model_xgb.pkl')
        with open(model_path, 'rb') as f:
            self.model = pickle.load(f)

        # Load feature column names
        features_path = os.path.join(models_dir, 'feature_columns.json')
        with open(features_path, 'r') as f:
            self.feature_columns = json.load(f)

        # Load model results for the /info endpoint
        results_path = os.path.join(base_dir, 'results', 'model_results.csv')
        if os.path.exists(results_path):
            self.results = pd.read_csv(results_path)
        else:
            self.results = None

        print(f"✅ Model loaded successfully!")
        print(f"   Features expected: {len(self.feature_columns)}")

    def predict(self, features_dict: dict) -> dict:
        """
        Make a single prediction.

        Args:
            features_dict: Dictionary of feature_name → value

        Returns:
            Dictionary with prediction and metadata
        """

        # Create feature array in correct order
        feature_values = []
        missing_features = []

        for col in self.feature_columns:
            if col in features_dict:
                feature_values.append(features_dict[col])
            else:
                feature_values.append(0)  # Default for missing features
                missing_features.append(col)

        # Make prediction
        X = np.array([feature_values])
        raw_prediction = self.model.predict(X)[0]

        # Clip to non-negative (can't sell negative items)
        prediction = max(0, round(float(raw_prediction), 1))

        # Determine confidence level based on input completeness
        completeness = (len(self.feature_columns) - len(missing_features)) / len(self.feature_columns)

        if completeness >= 0.9:
            confidence = "high"
        elif completeness >= 0.7:
            confidence = "medium"
        else:
            confidence = "low"

        # Generate ordering recommendation
        if prediction > 500:
            recommendation = "High demand expected — increase stock order"
        elif prediction > 200:
            recommendation = "Normal demand — maintain standard order quantity"
        elif prediction > 50:
            recommendation = "Low demand — reduce order to minimize waste"
        else:
            recommendation = "Very low demand — order minimum quantity only"

        return {
            "predicted_demand": prediction,
            "unit": "items",
            "confidence": confidence,
            "features_provided": len(features_dict),
            "features_expected": len(self.feature_columns),
            "features_missing": len(missing_features),
            "recommendation": recommendation
        }

    def get_model_info(self) -> dict:
        """Return model metadata and performance metrics."""

        info = {
            "model_type": "LightGBM Regressor",
            "num_features": len(self.feature_columns),
            "feature_names": self.feature_columns,
            "training_metrics": {
                "MAPE": "19.45%",
                "MAE": 131.2,
                "RMSE": 225.7,
                "R2": 0.8887
            },
            "baseline_comparison": {
                "baseline_method": "7-Day Moving Average",
                "baseline_MAPE": "38.42%",
                "improvement": "49.4% error reduction"
            },
            "business_impact": {
                "estimated_annual_waste_reduction": "$127,000",
                "stores_covered": 10,
                "categories_covered": 10
            }
        }

        if self.results is not None:
            info["all_models_compared"] = self.results.to_dict(orient='records')

        return info